### ISSUE TITLE
How to set background color for the gridview

### ISSUE THREAD

**Issue by nihp** [saleel/react-native-super-grid#87] opened 2019-04-01 11:30 UTC
I am using Gridview + FastImage ===> I need to change the background of the image.

I have set ImageBackground component and background color also. But it not worked for me.

**Comment by saleel** [comment] 2019-04-02 06:13
Please show sample code, and screenshot of the result.

**Comment by nihp** [comment] 2019-04-06 07:20
<GridView 
  spacing={5} 
  itemDimension={gridWidth} 
  items={this.renderItems()} 
  style={{backgroundColor: 'white'}} 
  renderItem={this.renderGrid.bind(this)} 
/> 

// Render grid method 
renderGrid() { 
  return(
    <ImageBackground 
      style={{backgroundColor:'#D1D1D1', aspectRatio:4/5}}
    >
      <FastImage 
        resizeMode={FastImage.resizeMode.contain} 
        source={{uri: item.uri}}
      /> 
    </ImageBackground> 
  ) 
}

**Comment by saleel** [comment] 2019-04-06 07:42
GridView component renders whatever you put in renderGrid for each item. If something inside that is not working, most likely that code don't work outside GridView too.
The default example in the readme file itself is demonstrating GridView with different color backgrounds (though not with images).

I haven't used ImageBackground or FastImage myself, so I can't be of much help. Maybe, you have to pass `{width: '100%', height: '100%'}` in styles prop to ImageBackground

I am closing this issue now, as I believe this is outside the scope of this library. If you find out the issue is because of this component, please reopen.

**Closed by saleel** 2019-04-06 07:42 UTC

**Comment by nihp** [comment] 2019-04-06 10:52
I have used onLoad props in fastlane solved my issue
